package oop_uas_c_2301010266;

import static oop_uas_c_2301010266.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Florentina Minovela Nasa
 * Tanggal : 28 Juni 2025
 */
public class fprodukkue extends javax.swing.JFrame {
    DefaultTableModel DTM = new DefaultTableModel();
    
    /**
     * Creates new form fprodukkue
     */
    public fprodukkue() throws SQLException {
        initComponents();
        
        tblproduk.setModel(DTM);
        DTM.addColumn("Kode");
        DTM.addColumn("Nama Produk");
        DTM.addColumn("Deskripsi");
        DTM.addColumn("Harga");
        DTM.addColumn("Stok");
        
        lsdtproduk();
        clearform();
        tombol(false);
        cTambah.setEnabled(true);
        cTutup.setEnabled(true);
        fieldAktif(false);
  
    }
    
    private void tombol(boolean opsi){
        cTambah.setEnabled(opsi);
        cUbah.setEnabled(opsi);
        cHapus.setEnabled(opsi);
        cTutup.setEnabled(opsi);
    }
    
    private void fieldAktif(boolean opsi){
        txKode.setEditable(opsi);
        txNama.setEditable(opsi);
        txDeskripsi.setEditable(opsi);
        txHarga.setEditable(opsi);
        txStok.setEditable(opsi); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txKode = new javax.swing.JTextField();
        txNama = new javax.swing.JTextField();
        txHarga = new javax.swing.JTextField();
        txStok = new javax.swing.JTextField();
        cTambah = new javax.swing.JButton();
        cUbah = new javax.swing.JButton();
        cHapus = new javax.swing.JButton();
        cTutup = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproduk = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txDeskripsi = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("DATA PRODUK KUE");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Kode");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nama Produk");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Deskripsi");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Harga (Rp)");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Stok");

        txKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txKodeActionPerformed(evt);
            }
        });

        txHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHargaActionPerformed(evt);
            }
        });

        cTambah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cTambah.setForeground(new java.awt.Color(51, 51, 255));
        cTambah.setText("Tambah");
        cTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTambahActionPerformed(evt);
            }
        });

        cUbah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cUbah.setForeground(new java.awt.Color(51, 51, 255));
        cUbah.setText("Ubah");
        cUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUbahActionPerformed(evt);
            }
        });

        cHapus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cHapus.setForeground(new java.awt.Color(51, 51, 255));
        cHapus.setText("Hapus");
        cHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHapusActionPerformed(evt);
            }
        });

        cTutup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cTutup.setForeground(new java.awt.Color(51, 51, 255));
        cTutup.setText("Tutup");
        cTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTutupActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("BAKEDREAM KEEP");

        tblproduk.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblproduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblprodukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproduk);

        jScrollPane3.setViewportView(txDeskripsi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txNama)
                            .addComponent(txKode)
                            .addComponent(txStok)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cTambah)
                                .addGap(18, 18, 18)
                                .addComponent(cUbah)
                                .addGap(18, 18, 18)
                                .addComponent(cHapus)
                                .addGap(18, 18, 18)
                                .addComponent(cTutup))
                            .addComponent(txHarga)
                            .addComponent(jScrollPane3))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTambah)
                    .addComponent(cUbah)
                    .addComponent(cHapus)
                    .addComponent(cTutup))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txKodeActionPerformed

    private void txHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHargaActionPerformed

    private void cTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTambahActionPerformed
      if(cTambah.getText().equals("Tambah")) {
      clearform();
      fieldAktif(true);
      
      cTambah.setText("Simpan");
      cTutup.setText("Batal");
      cUbah.setEnabled(false);
      cHapus.setEnabled(false);
      } else {
          try {
              storeData();
              lsdtproduk();
          } catch (SQLException ex) {
              Logger.getLogger(fprodukkue.class.getName()).log(Level.SEVERE, null, ex);
          }
        cTambah.setText("Tambah");
        cTutup.setText("Tutup");
        clearform();
        fieldAktif(false);
      }
    }//GEN-LAST:event_cTambahActionPerformed

    private void tblprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblprodukMouseClicked
        txKode.setText(tblproduk.getValueAt(tblproduk.getSelectedRow(), 0).toString());
        txNama.setText(tblproduk.getValueAt(tblproduk.getSelectedRow(), 1).toString());
        txDeskripsi.setText(tblproduk.getValueAt(tblproduk.getSelectedRow(), 2).toString());
        txHarga.setText(tblproduk.getValueAt(tblproduk.getSelectedRow(), 3).toString());
        txStok.setText(tblproduk.getValueAt(tblproduk.getSelectedRow(), 4).toString());
     
        cUbah.setEnabled(true);
        cHapus.setEnabled(true);
    }//GEN-LAST:event_tblprodukMouseClicked

    private void cTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTutupActionPerformed
       if(cTutup.getText().equals("Tutup")) {
           int opsi = JOptionPane.showOptionDialog(this, "Anda Yakin Ingin Menutup Aplikasi?", "Konfirmasi Tutup Aplikasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
           if (opsi==JOptionPane.YES_OPTION){
             System.exit(0);  
           }  
        } else{
           cTutup.setText("Tutup");
           cTambah.setText("Tambah");
           cUbah.setText("Ubah");
           cTambah.setEnabled(true);
           cUbah.setEnabled(false);
           fieldAktif(false);
           clearform();
        } 
    }//GEN-LAST:event_cTutupActionPerformed

    private void cUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUbahActionPerformed
       if(cUbah.getText().equals("Ubah")) {
           cUbah.setText("Simpan");
           cTutup.setText("Batal");
           cTambah.setEnabled(false);
           cHapus.setEnabled(false);
           fieldAktif(true);
           txKode.setEditable(false);
        } else {
           
           try {
               updateData();
               lsdtproduk();
           } catch (SQLException ex) {
               Logger.getLogger(fprodukkue.class.getName()).log(Level.SEVERE, null, ex);
           }
           
          cUbah.setText("Ubah");
          cTutup.setText("Tutup");
          cTambah.setEnabled(true);
          cUbah.setEnabled(false);
          fieldAktif(false);
          clearform();
        }
    }//GEN-LAST:event_cUbahActionPerformed

    private void cHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHapusActionPerformed
        int opsi = JOptionPane.showOptionDialog(this, "Anda Yakin Untuk Menghapus Data " +txKode.getText() +"?", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
           if (opsi==JOptionPane.YES_OPTION){
            try{
                destroyData();
                lsdtproduk();
                clearform();
                cHapus.setEnabled(false);
                cUbah.setEnabled(false);
                
            } catch (SQLException ex){
                System.out.print("Error");
             } 
            }
    }//GEN-LAST:event_cHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fprodukkue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fprodukkue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fprodukkue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fprodukkue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                   new fprodukkue().setVisible(true); 
                } catch (SQLException ex) {
                    Logger.getLogger(fprodukkue.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cTambah;
    private javax.swing.JButton cTutup;
    private javax.swing.JButton cUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblproduk;
    private javax.swing.JTextPane txDeskripsi;
    private javax.swing.JTextField txHarga;
    private javax.swing.JTextField txKode;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txStok;
    // End of variables declaration//GEN-END:variables
    
    private void lsdtproduk() throws SQLException {
      Connection cnn = koneksi();
      
      DTM.getDataVector().removeAllElements();
      DTM.fireTableDataChanged();
      
      if(!cnn.isClosed()){
          PreparedStatement PS = cnn.prepareStatement("SELECT * FROM produkkue;");
          ResultSet RS = PS.executeQuery();
        
          while(RS.next()){
            Object[] dtaproduk = new Object[5];
              dtaproduk [0] = RS.getString("Kode");
              dtaproduk [1] = RS.getString("NamaProduk");
              dtaproduk [2] = RS.getString("Deskripsi");
              dtaproduk [3] = RS.getString("Harga");
              dtaproduk [4] = RS.getString("Stok");
              
              DTM.addRow(dtaproduk);
           } 
        }
      
    }
    
    private void clearform() {
        txKode.setText("");
        txNama.setText("");
        txDeskripsi.setText("");
        txHarga.setText("");
        txStok.setText("");
    }
    
    private void storeData() throws SQLException {
        Connection cnn = koneksi();
        String kode = txKode.getText();
        String nama = txNama.getText();
        String deskripsi = txDeskripsi.getText();
        String harga = txHarga.getText();
        String stok = txStok.getText();
        
        if(!cnn.isClosed()) {
            PreparedStatement PS = cnn.prepareStatement("INSERT INTO produkkue(Kode,NamaProduk,Deskripsi,Harga,Stok) VALUES(?,?,?,?,?)");
            PS.setString(1, kode);
            PS.setString(2, nama);
            PS.setString(3, deskripsi);
            PS.setString(4, harga);
            PS.setString(5, stok);
            PS.executeUpdate();
            cnn.close();
        }
    }
    
    private void updateData() throws SQLException {
       Connection cnn = koneksi();
       String kode = txKode.getText();
       String nama = txNama.getText();
       String deskripsi = txDeskripsi.getText();
       String harga = txHarga.getText();
       String stok = txStok.getText();
       
       if(!cnn.isClosed()){
          PreparedStatement PS = cnn.prepareStatement("UPDATE produkkue SET NamaProduk=?,Deskripsi=?,Harga=?,Stok=? WHERE Kode=?;");
           PS.setString(1, nama);
           PS.setString(2, deskripsi);
           PS.setString(3, harga);
           PS.setString(4, stok);
           PS.setString(5, kode);
           PS.executeUpdate();
           cnn.close(); 
       }
    }
    
    private void destroyData() throws SQLException {
       Connection cnn = koneksi();
       String kode = txKode.getText();
     
       if(!cnn.isClosed()){
          PreparedStatement PS = cnn.prepareStatement("DELETE FROM produkkue WHERE Kode=?;");
           PS.setString(1, kode);
           PS.executeUpdate();
           cnn.close(); 
       }
    }
      
}


